language: node_js
services:
  - mongodb
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '6'
before_script:
  - yarn global add codecov
  - sudo pip install mkdocs
script:
  - yarn run lint
  - yarn run lint-messages
  - yarn run cover
  - codecov
  - yarn run build
  - mkdocs
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
